<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.0</TargetFramework>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>SeleZenZHMod</AssemblyName>
    <RootNamespace>SeleZenZHMod</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="Patches\*.js" />
  </ItemGroup>
</Project>
